// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID        int64
	UserID    int64
	Username  string
	Address   string
	Seed      string
	CreatedAt pgtype.Timestamptz
}

type State struct {
	UserID    int64
	State     string
	Data      map[string]interface{}
	Meta      map[string]interface{}
	CreatedAt pgtype.Timestamptz
}
