// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type State struct {
	UserID    int64
	State     string
	Data      map[string]interface{}
	Meta      map[string]interface{}
	CreatedAt pgtype.Timestamptz
}
