// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	CreateBalance(ctx context.Context, arg CreateBalanceParams) error
	CreateState(ctx context.Context, arg CreateStateParams) error
	GetBalances(ctx context.Context, userID int64) ([]Balance, error)
	GetState(ctx context.Context, userID int64) (State, error)
	UpdateBalancePending(ctx context.Context, arg UpdateBalancePendingParams) error
	UpdateBalanceSent(ctx context.Context, arg UpdateBalanceSentParams) error
}

var _ Querier = (*Queries)(nil)
