---
name: deploy
on:
  push:
    branches: [master, develop]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
      - name: Build application
        run: make build
      - name: Deploy artifact to remote host
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
        run: |-
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key
          if [ "${{ github.ref_name }}" == "master" ]; then
            REMOTE_PATH="/usr/local/bin/panarchybot"
          elif [ "${{ github.ref_name }}" == "develop" ]; then
            REMOTE_PATH="/usr/local/bin/panarchybotdev"
          else
            echo "Branch not supported for deployment" && exit 1
          fi
          scp -v -o StrictHostKeyChecking=no -i private_key dist/panarchybot "$REMOTE_USER@$REMOTE_HOST:$REMOTE_PATH"
          rm private_key
